squid:
  build: squid/.
  environment:
    - "DISK_CACHE_SIZE=5000"
    - "MAX_CACHE_OBJECT=1000"
    # - "SQUID_DIRECTIVES_ONLY=true"
    - "SQUID_DIRECTIVES=refresh_pattern . 0 0 1 refresh-ims\nstore_id_program /usr/lib/squid3/storeid_file_rewrite /mnt/rewrite.conf"
  net: "host"
  volumes:
    - /buildarea/kscherer/squid:/var/cache/squid3
    - $PWD:/mnt

tproxy:
  build: iptables_docker/.
  net: "host"
  privileged: true
